version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    env_file: .env
    volumes:
      - redis-data:/data
    restart: on-failure
    ports:
      - '6379:6379'

  bot:
    build: .
    command: python3 -m bot
    stop_signal: SIGINT
    env_file: .env
    restart: always
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
