version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - '5432:5432'

  bot:
    build: .
    command: python3 -m bot
    stop_signal: SIGINT
    env_file: .env
    restart: always
    depends_on:
      - postgres

volumes:
  postgres-data:
